Try to design map items
MerginMaps/mobile pull request #2852
Opened 2023-10-11 12:44 UTC by iiLubos

In Qt6, there is a problem with creating a shadow...

2023-10-24 07:57 UTC, iiLubos commented
Ready for review

2023-10-24 13:55 UTC, PeterPetrik reviewed
LGTM

2023-10-25 11:30 UTC, tomasMizera commented on app/qmlV2/component/MMMapLabel.qml
> +import Qt5Compat.GraphicalEffects
Seems not to be needed

2023-10-25 11:31 UTC, tomasMizera commented on app/qmlV2/component/MMMapLabel.qml
> +  height: Style.commonItemHeight
What is "commonItemHeight"? Let's be more specific and have `mapItemHeight`

2023-10-25 11:31 UTC, tomasMizera commented on app/qmlV2/component/MMMapLabel.qml
> +  visible: control.text.length > 0
Let's not bind the visible state, what is it good for? :)

2023-10-25 11:33 UTC, tomasMizera commented on app/qmlV2/component/MMMapLabel.qml
> +      leftPadding: Style.commonSpacing
Let's not use "common" spacing. It will backfire later. Let's have specific spacing for map items

2023-10-25 11:36 UTC, tomasMizera requested changes
See comments :)

2023-10-31 13:22 UTC, iiLubos commented
Applied all the review comments.
Support for an icon inside the Map label.

2023-11-07 14:27 UTC, tomasMizera requested changes
Bla bla test

2023-11-14 11:33 UTC, tomasMizera approved these changes

2023-11-14 15:04 UTC, merged