Added Input with right icon
MerginMaps/mobile pull request #2972
Opened 2023-12-20 11:02 UTC by iiLubos

![image](https://github.com/MerginMaps/mobile/assets/72412563/67670b87-b67b-4dd2-a0dd-cf007a0f0a03)

        MMInputWithRightIconEditor {
          title: "MMInputWithRightIconEditor"
          placeholderText: "Placeholder"
          warningMsg: text.length > 0 ? "" : "Press button to scan"
          iconSource: __style.qrCodeIcon
          onRightActionClicked: text = "Scanned text ..."
        }

2023-12-21 07:26 UTC, tomasMizera commented on app/qml/inputs/MMIconInputEditor.qml
Let's make this qrcode/calendar instead of another generic component

2023-12-21 07:57 UTC, tomasMizera requested changes
Create qrcode and calendar inputs

2024-01-04 17:33 UTC, PeterPetrik commented on app/qml/components/MMAmPmSwitch.qml
> +// Prepared switch, but to used yet
typo?

2024-01-04 17:35 UTC, PeterPetrik commented on app/qml/components/MMAmPmSwitch.qml
> +/***************************************************************************
wondering if not to put all "sub" components to subfolder (`components/calendar`) and just keep the calendar that can be used from rest of the application in `comonents` folder?

2024-01-17 14:06 UTC, tomasMizera reviewed
Minor comments :)

2024-01-19 07:46 UTC, tomasMizera approved these changes

2024-01-19 07:55 UTC, merged