WIP - Position tracking button visibility adjustment
MerginMaps/mobile pull request #3137
Opened 2024-03-13 01:35 UTC by VitorVieiraZ

A

2024-03-13 06:39 UTC, tomasMizera reviewed
Looking good, just a few notes

2024-03-13 06:39 UTC, tomasMizera commented on app/qml/components/MMToolbar.qml
> +      if ( m.get(j).visibilityMode === false )
You might need to first check if the `visibilityMode` exists. There are buttons like `MMToolbarLongButton` that does not have this new property.

```suggestion
      if ( m.get(j).visibilityMode && m.get(j).visibilityMode === false )
```

2024-03-13 06:39 UTC, tomasMizera commented on app/qml/components/MMToolbar.qml
> +    for ( var j = m.count - 1 ; j >= 0 ; j-- )
While you are here, would it be please possible to rename these one-letter variables to something meaningful to make the code more readable? Something like `m -> buttonModel`, `c -> buttonsCount` and `w -> buttonWidth`. Also please change `var` to `let`

2024-03-13 10:11 UTC, tomasMizera commented on app/qml/components/MMToolbar.qml
> +    var c = m.count
```suggestion
  let filteredbuttons = []

    for ( var j = m.count - 1 ; j >= 0 ; j-- )
    {
      if ( m.get(j).visibilityMode || m.get(j).visibilityMode === true )
      {
          filteredbuttons.append( m.get(j) );
      }
    }

    // c = filteredbuttons.length
    // ... replace m.get(i) with filteredbuttons[i]
```

2024-03-14 11:55 UTC, tomasMizera requested changes
It does not work in this situation:

 - Open project with position tracking enabled
 - Position tracking button is there ✔️ 
 - Go back to projects
 - Open project _without_ position tracking
 - Position tracking button is still visible ❌

<img width="400" alt="Screenshot 2024-03-14 at 12 53 22" src="https://github.com/MerginMaps/mobile/assets/22449698/28c20f44-03f5-4fc5-922b-755924a76d5b">

2024-03-14 11:55 UTC, tomasMizera commented on app/qml/components/MMToolbar.qml
> +    var buttonModel = root.model
```suggestion
    let buttonModel = root.model
```

2024-03-14 11:55 UTC, tomasMizera commented on app/qml/components/MMToolbar.qml
> +    var buttonWidth = buttonView.width
```suggestion
    let buttonWidth = buttonView.width
```

2024-03-14 11:55 UTC, tomasMizera commented on app/qml/components/MMToolbar.qml
>      var button
```suggestion

```

2024-03-14 11:55 UTC, tomasMizera commented on app/qml/components/MMToolbar.qml
> +        button = filteredbuttons[i]
```suggestion
        let button = filteredbuttons[i]
```

2024-03-14 20:27 UTC, VitorVieiraZ commented
Fixed

2024-03-15 05:26 UTC, tomasMizera approved these changes

2024-03-15 05:26 UTC, merged