Adjustment of the text displayed during synchronization
MerginMaps/mobile pull request #3168
Opened 2024-03-22 02:04 UTC by VitorVieiraZ

From "Synchronising..." to "Please don't close the app." 

<img src="https://github.com/MerginMaps/mobile/assets/155513369/d8d10242-7847-4e96-8923-3e26e2e7f962" width="300">

2024-03-22 07:16 UTC, tomasMizera commented
Hi @VitorVieiraZ 

 - Would it be possible to adjust it like this

<img width="520" alt="image" src="https://github.com/MerginMaps/mobile/assets/22449698/d70a545a-0e57-426b-a6c8-c28dc4483fe2">

- You need to add the text "Synchronising project changes" to `ProjectsModel::data` when returning `ProjectDescription`. There is a flag `ProjectSyncPending` that you can use to differentiate if the project is currently being synchronised

2024-03-22 07:17 UTC, tomasMizera requested changes
See my comment

2024-03-22 14:15 UTC, VitorVieiraZ commented
<img src="https://github.com/MerginMaps/mobile/assets/155513369/73c839ab-3765-4935-8a18-2dff88791f6e" width="300">
<img src="https://github.com/MerginMaps/mobile/assets/155513369/5fc4315c-0e7f-4097-8835-166ab06ef564" width="300">

2024-03-23 11:56 UTC, PeterPetrik approved these changes

2024-03-23 11:57 UTC, merged