WIP - Improving UX by hiding editing buttons for readers and guests of a project
MerginMaps/mobile pull request #3682
Opened 2024-11-18 15:34 UTC by VitorVieiraZ

Resolves #3174

2025-01-06 15:41 UTC, tomasMizera requested changes

2025-01-15 14:30 UTC, tomasMizera requested changes

2025-01-15 14:30 UTC, tomasMizera commented on app/activeproject.cpp
> +                              , MerginApi *merginApi
Let's get rid of the dependency according to what we discussed

2025-01-20 13:00 UTC, tomasMizera commented on core/coreutils.h
> +    static bool replaceValueInJson( const QString &filePath, const QString &key, const QJsonValue &value );
Let's add some unit tests for the new method please

2025-01-20 17:16 UTC, tomasMizera reviewed
Just small adjustments and we are ready to go 🚀

2025-01-20 17:16 UTC, tomasMizera commented on app/test/testcoreutils.cpp
> +    QVERIFY( CoreUtils::replaceValueInJson( testFilePath, "value", 456 ) );
I would add another key to test strings (now you test int)

2025-01-20 17:16 UTC, tomasMizera commented on core/merginapi.h
> +    QString getCachedProjectRole( const QString &projectFullName ) const;
Would be nice to have some explanation comments here

2025-01-20 17:16 UTC, tomasMizera commented on app/test/testmerginapi.cpp
> +  QCOMPARE( cachedRole, newRole );
This is fine, but we now need to test the actual behaviour - communication with the server. Let's call the `reloadProjectRole` method and check if the cached role will be back to `owner` as it should :)

2025-01-20 17:16 UTC, tomasMizera commented on app/test/testmerginapi.cpp
> +  QCOMPARE( cachedRole, newRole );
Just a tip - it is handy to qcompare to real values instead of variables (if possible). This way unit tests are more readable.

```suggestion
  QCOMPARE( cachedRole, "reader" );
```

2025-01-21 15:54 UTC, tomasMizera commented on app/test/testmerginapi.cpp
> +
Shouldn't we call server to update our project role here?

2025-01-21 16:35 UTC, VitorVieiraZ commented on app/test/testmerginapi.cpp
> +
We could, but the result would be unpredictable, since we can't manipulate the role in the server from here.

2025-01-22 09:45 UTC, tomasMizera commented on app/test/testmerginapi.cpp
> +
But that is what we want, no? You manipulated it locally to be "reader" and now we want to make sure that the next time we update it from server, the role goes back to what it should be - "owner". Otherwise we are just testing a small subset of the functionality (changing json value)

2025-01-23 16:08 UTC, tomasMizera approved these changes
🚀

2025-01-23 16:23 UTC, merged

2025-01-23 16:23 UTC, tomasMizera commented
Merging, CI will pass on master 🙃